# Binary Predicter

### Import Libraries

In [76]:
import pandas as pd  
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
sns.set()

### Load Data

In [77]:
df=pd.read_csv('datasets/Binary predictors.csv')

In [78]:
df.sample(5)

SAT Admitted  Gender
11   1880      Yes  Female
17   1634       No    Male
92   1735      Yes  Female
64   1786      Yes    Male
136  1974      Yes  Female

In [79]:
m_gender={'Male':0,'Female':1}
m={'No':0,'Yes':1}
df['Admitted']=df['Admitted'].map(m)
df['Gender']=df['Gender'].map(m_gender)

In [80]:
df.sample(5)

SAT  Admitted  Gender
139  1557         0       0
60   1550         0       0
33   2020         1       0
24   1720         1       1
81   1808         1       1

### Declare dependent and independent variables

In [83]:
y=df['Admitted']
x1=df[['SAT','Gender']]

### Logistic Regression

In [84]:
x=sm.add_constant(x1)
reg_line=sm.Logit(y,x)
results_log=reg_line.fit()

Optimization terminated successfully.
         Current function value: 0.120117
         Iterations 10


In [85]:
results_log.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:               Admitted   No. Observations:                  168
Model:                          Logit   Df Residuals:                      165
Method:                           MLE   Df Model:                            2
Date:                Tue, 20 Dec 2022   Pseudo R-squ.:                  0.8249
Time:                        16:21:15   Log-Likelihood:                -20.180
converged:                       True   LL-Null:                       -115.26
Covariance Type:            nonrobust   LLR p-value:                 5.118e-42
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const        -68.3489     16.454     -4.154      0.000    -100.598     -36.100
SAT            0.0406      0.010      4.129      0.000       0.021       0.060
Gender         1.9449      0.846      2.299      0.022       0.287       3.603
==============================================================================

Possibly complete quasi-separation: A fraction 0.27 of observations can be
perfectly predicted. This might indicate that there is complete
quasi-separation. In this case some parameters will not be identified.
"""

### Accuracy

In [86]:
np.set_printoptions(formatter={'float':lambda x: "{0:0.2f}".format(x)})
results_log.predict()

array([0.00, 1.00, 1.00, 0.23, 0.02, 0.99, 1.00, 1.00, 1.00, 0.01, 1.00,
       1.00, 0.76, 0.00, 0.60, 1.00, 0.11, 0.12, 0.51, 1.00, 1.00, 1.00,
       0.00, 0.01, 0.97, 1.00, 0.48, 0.99, 1.00, 0.99, 0.00, 0.83, 0.25,
       1.00, 1.00, 1.00, 0.31, 1.00, 0.23, 0.00, 0.02, 0.45, 1.00, 0.00,
       0.99, 0.00, 0.99, 0.00, 0.00, 0.01, 0.00, 1.00, 0.92, 0.02, 1.00,
       0.00, 0.37, 0.98, 0.12, 1.00, 0.00, 0.78, 1.00, 1.00, 0.98, 0.00,
       0.00, 0.00, 1.00, 0.00, 0.78, 0.12, 0.00, 0.99, 1.00, 1.00, 0.00,
       0.30, 1.00, 1.00, 0.00, 1.00, 1.00, 0.85, 1.00, 1.00, 0.00, 1.00,
       1.00, 0.89, 0.83, 0.00, 0.98, 0.97, 0.00, 1.00, 1.00, 0.03, 0.99,
       0.96, 1.00, 0.00, 1.00, 0.01, 0.01, 1.00, 1.00, 1.00, 0.00, 0.00,
       0.02, 0.33, 0.00, 1.00, 0.09, 0.00, 0.97, 0.00, 0.75, 1.00, 1.00,
       0.01, 0.01, 0.00, 1.00, 0.00, 0.99, 0.57, 0.54, 0.87, 0.83, 0.00,
       1.00, 0.00, 0.00, 0.00, 1.00, 0.04, 0.00, 0.01, 1.00, 0.99, 0.52,
       1.00, 1.00, 0.05, 0.00, 0.00, 0.00, 0.68, 1.

In [87]:
np.array(df['Admitted'])

array([0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0], dtype=int64)

In [88]:
results_log.pred_table()

array([[69.00, 5.00],
       [4.00, 90.00]])

### Confusion Matrix

In [89]:
cm_df=pd.DataFrame(results_log.pred_table())
cm_df.columns=['Predicted 0','Predicted 1']
cm_df=cm_df.rename(index={0:'Actual 0',1:'Actual 1'})
cm_df

Predicted 0  Predicted 1
Actual 0         69.0          5.0
Actual 1          4.0         90.0

In [90]:
cm=np.array(cm_df)
accuracy_train=(cm[0,0]+cm[1,1])/cm.sum()
accuracy_train

0.9464285714285714

### Testing the model

In [100]:
test=pd.read_csv('datasets/Test dataset.csv',on_bad_lines='skip')

In [101]:
test.sample(5)

SAT Admitted  Gender
11  2039      Yes  Female
8   1930      Yes  Female
9   1708      Yes    Male
6   1731      Yes  Female
17  1500       No  Female

In [102]:
m_gender={'Male':0,'Female':1}
m={'No':0,'Yes':1}
test['Admitted']=test['Admitted'].map(m)
test['Gender']=test['Gender'].map(m_gender)

In [103]:
test.sample(5)

SAT  Admitted  Gender
2   1762         1       1
0   1323         0       0
15  1876         1       1
14  1726         0       0
6   1731         1       1

In [104]:
test_actual=test['Admitted']
test_data=test.drop(['Admitted'],axis=1)
test_data=sm.add_constant(test_data)
#test_data=test_data[x.columns.values]
test_data.sample(5)

const   SAT  Gender
12    1.0  1681       1
18    1.0  1900       0
3     1.0  1777       0
2     1.0  1762       1
17    1.0  1500       1

### Confusion Matrix

In [110]:
def confusion_matrix(data,actual_values,model):
    pred_values=model.predict(data)
    bins=np.array([0,0.5,1])
    cm=np.histogram2d(actual_values,pred_values,bins=bins)[0]
    accuracy=((cm[0,0]+cm[1,1])/cm.sum())
    return cm,accuracy

In [111]:
cm=confusion_matrix(test_data,test_actual,results_log)

In [112]:
cm

(array([[5.00, 1.00],
        [1.00, 12.00]]),
 0.8947368421052632)

In [113]:
cm=pd.DataFrame(cm[0])
cm_df.columns=['Predicted 0','Predicted 1']
cm_df=cm_df.rename(index={0:'Actual 0',1:'Actual 1'})
cm_df

Predicted 0  Predicted 1
Actual 0         69.0          5.0
Actual 1          4.0         90.0