### Actual TensorFlow Intro


In [19]:
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np

### Data generation

In [20]:
observations = 1000

xs=np.random.uniform(-10,10,size=(observations,1))
zs=np.random.uniform(-10,10,(observations,1))

generated_inputs=np.column_stack((xs,zs))

noise=np.random.uniform(-1,1,(observations,1))

generated_targets= 2*xs -3*zs + 5 + noise

np.savez('TF_intro',inputs=generated_inputs,targets=generated_targets)

### Solving with TensorFlow

In [21]:
training_data=np.load('TF_intro.npz')

In [22]:
input_size=2
output_size=1

model=tf.keras.Sequential([
    tf.keras.layers.Dense(output_size)
])
model.compile(optimizer='sgd',loss='mean_squared_error')
model.fit(training_data['inputs'],training_data['targets'],epochs=100,verbose=2)

Epoch 1/100
32/32 - 0s - loss: 36.1736 - 447ms/epoch - 14ms/step
Epoch 2/100
32/32 - 0s - loss: 4.2135 - 43ms/epoch - 1ms/step
Epoch 3/100
32/32 - 0s - loss: 1.3945 - 40ms/epoch - 1ms/step
Epoch 4/100
32/32 - 0s - loss: 0.6383 - 37ms/epoch - 1ms/step
Epoch 5/100
32/32 - 0s - loss: 0.4238 - 46ms/epoch - 1ms/step
Epoch 6/100
32/32 - 0s - loss: 0.3683 - 43ms/epoch - 1ms/step
Epoch 7/100
32/32 - 0s - loss: 0.3494 - 67ms/epoch - 2ms/step
Epoch 8/100
32/32 - 0s - loss: 0.3412 - 61ms/epoch - 2ms/step
Epoch 9/100
32/32 - 0s - loss: 0.3357 - 56ms/epoch - 2ms/step
Epoch 10/100
32/32 - 0s - loss: 0.3368 - 46ms/epoch - 1ms/step
Epoch 11/100
32/32 - 0s - loss: 0.3396 - 35ms/epoch - 1ms/step
Epoch 12/100
32/32 - 0s - loss: 0.3392 - 33ms/epoch - 1ms/step
Epoch 13/100
32/32 - 0s - loss: 0.3419 - 39ms/epoch - 1ms/step
Epoch 14/100
32/32 - 0s - loss: 0.3385 - 36ms/epoch - 1ms/step
Epoch 15/100
32/32 - 0s - loss: 0.3398 - 38ms/epoch - 1ms/step
Epoch 16/100
32/32 - 0s - loss: 0.3361 - 46ms/epoch - 1ms/ste

### Extract the weights and bias

In [23]:
model.layers[0].get_weights()

[array([[ 2.011462 ],
        [-2.9551315]], dtype=float32),
 array([4.9673843], dtype=float32)]

In [24]:
weights=model.layers[0].get_weights()[0]
weights

array([[ 2.011462 ],
       [-2.9551315]], dtype=float32)

In [25]:
bias=model.layers[0].get_weights()[1]
bias

array([4.9673843], dtype=float32)

### Extract the outputs

In [26]:
model.predict_on_batch(training_data['inputs']).round(1)[10:20]

array([[-10.2],
       [  7.2],
       [ -0.3],
       [ 12. ],
       [-27.1],
       [-13.7],
       [-34.8],
       [  4.2],
       [ -4.8],
       [ 16.7]], dtype=float32)

In [27]:
training_data['targets'].round(1)[10:20]

array([[-10.4],
       [  7.7],
       [ -0.3],
       [ 12.9],
       [-26.7],
       [-13.3],
       [-35.9],
       [  4.5],
       [ -4.7],
       [ 17. ]])

### Customizing TF2 Model

In [31]:
training_data=np.load('TF_intro.npz')

In [35]:
input_size=2
output_size=1

model=tf.keras.Sequential([
    tf.keras.layers.Dense(output_size,
                          kernel_initializer=tf.random_uniform_initializer(minval=-0.1,maxval=0.1),
                          bias_initializer=tf.random_uniform_initializer(minval=-0.1,maxval=0.1))
])
custom_optimizer=tf.keras.optimizers.SGD(learning_rate=0.01)
model.compile(optimizer=custom_optimizer,loss='mean_squared_error')
model.fit(training_data['inputs'],training_data['targets'],epochs=100,verbose=2)

Epoch 1/100
32/32 - 1s - loss: 31.7824 - 545ms/epoch - 17ms/step
Epoch 2/100
32/32 - 0s - loss: 4.4198 - 52ms/epoch - 2ms/step
Epoch 3/100
32/32 - 0s - loss: 1.4425 - 54ms/epoch - 2ms/step
Epoch 4/100
32/32 - 0s - loss: 0.6602 - 53ms/epoch - 2ms/step
Epoch 5/100
32/32 - 0s - loss: 0.4285 - 48ms/epoch - 1ms/step
Epoch 6/100
32/32 - 0s - loss: 0.3639 - 58ms/epoch - 2ms/step
Epoch 7/100
32/32 - 0s - loss: 0.3431 - 52ms/epoch - 2ms/step
Epoch 8/100
32/32 - 0s - loss: 0.3457 - 57ms/epoch - 2ms/step
Epoch 9/100
32/32 - 0s - loss: 0.3452 - 50ms/epoch - 2ms/step
Epoch 10/100
32/32 - 0s - loss: 0.3418 - 50ms/epoch - 2ms/step
Epoch 11/100
32/32 - 0s - loss: 0.3393 - 48ms/epoch - 1ms/step
Epoch 12/100
32/32 - 0s - loss: 0.3445 - 46ms/epoch - 1ms/step
Epoch 13/100
32/32 - 0s - loss: 0.3373 - 50ms/epoch - 2ms/step
Epoch 14/100
32/32 - 0s - loss: 0.3392 - 52ms/epoch - 2ms/step
Epoch 15/100
32/32 - 0s - loss: 0.3457 - 32ms/epoch - 998us/step
Epoch 16/100
32/32 - 0s - loss: 0.3445 - 36ms/epoch - 1ms/s

In [36]:
weights=model.layers[0].get_weights()[0]
weights

array([[ 2.0068262],
       [-2.9930947]], dtype=float32)

In [37]:
bias=model.layers[0].get_weights()[1]
bias

array([4.96015], dtype=float32)